---
- name: Cleanup user for k8s
  include_tasks: cleanup-user.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - kubernetes_engine != "minikube"
  tags: [ never, cleanup ]

- name: Generate user for k8s
  include_tasks: create-user.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - kubernetes_engine == "minikube"
  tags: [ nocleanup ]